- name: Playbook1
  hosts: all

  tasks: 

  # - name: installation of service
  #   become: true
  #   apt: 
  #    name: ftp 
  #    state: latest 
  #   tags: ftp_sevice

  - name: print ansible user 
    debug:
      msg: "product  version name of ansible: {{ansible_product_version}}"
    when: ansible_product_version == "abc" and ansible_distribution == 'dgg' 
    tags: only_print 
    
  - name: print ansible user 
    debug:
      msg: "distribution name of ansible : {{ansible_distribution}}"
    tags: only_two
   

  - name: print ansible user 
    debug:
      msg: "ansible os name: {{ansible_os_family}}"