- name: Playbook1
  hosts: all
  # vars:
  #   URL: global.clouditz.com
  tasks:
   - name: print message_1
     debug:
      msg: "{{URL}}"
  # vars_files: files.yml
  # tasks:
  # - name: print message_1
  #   debug:
  #    msg: "{{URL}}"
  # vars:
  #   URL: hello bhai
 