- name: Playbook1
  hosts: all

  tasks: 

  # - name: installation of service
  #   become: true
  #   apt: 
  #    name: ftp 
  #    state: latest 
  #   tags: ftp_sevice

  - name: print ansible user 
    debug:
      msg: "ansible user: {{ansible_lsb.codename}}"
    tags: only_print 
    
  - name: print ansible user 
    debug:
      msg: "ansible user: {{ansible_lsb.codename}}"
    tags: only_two
    when: ansible_lsb.codename == "abc" and ansible_lsb.codename == 'dgg' 